[package]
name = "opcua-client"
version = "0.1.0"
description = "OPC UA client API"
authors = ["Adam Lock <locka99@gmail.com>"]
homepage = "https://github.com/locka99/opcua"
license = "MPL-2.0"
keywords = ["opcua","opc","ua"]
categories = ["embedded","network-programming"]

[dependencies]
url = "1.4.0"
log = "0.3.6"
chrono = "0.3"

[dependencies.opcua-core]
path = "../core"
