[package]
name = "opcua-simple-server"
version = "0.4.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]
chrono = "0.4"
log = "0.3"

[dependencies.opcua-types]
path = "../../types"
version = "0.4.0" # OPCUARustVersion

[dependencies.opcua-core]
path = "../../core"
version = "0.4.0" # OPCUARustVersion

[dependencies.opcua-server]
path = "../../server"
version = "0.4.0" # OPCUARustVersion

[dependencies.opcua-console-logging]
path = "../../console-logging"
version = "0.4.0" # OPCUARustVersion