[package]
name = "opcua-sample-client"
version = "0.1.0"
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]

[dependencies.opcua-types]
path = "../types"

[dependencies.opcua-client]
path = "../client"

[dependencies.opcua-core]
path = "../core"