language: rust
rust:
  - stable
  - nightly

before_install:
  - export RUST_BACKTRACE=1

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --package opcua-server -- --nocapture
  - cargo test --package opcua-core -- --nocapture
