[workspace]
members = ["types", "core", "client", "server", "integration", "samples/demo-server", "samples/simple-client", "samples/simple-server", "samples/chess-server", "samples/discovery-client", "tools/certificate-creator"]
