[package]
name = "opcua-certificate-creator"
version = "0.5.0" # OPCUARustVersion
description = "OPC UA certificate creator"
authors = ["Adam Lock <locka99@gmail.com>"]
homepage = "https://github.com/locka99/opcua"
license = "MPL-2.0"
keywords = ["opcua","opc","ua"]
categories = ["embedded","network-programming"]

[dependencies]
clap = "2.27"

[dependencies.opcua-types]
path = "../../types"
version = "0.5.0" # OPCUARustVersion

[dependencies.opcua-core]
path = "../../core"
version = "0.5.0" # OPCUARustVersion
