[package]
name = "certificate-creator"
version = "0.1.0"
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]
clap = "~2.19.0"
log = "0.3.6"

[dependencies.opcua-core]
path = "../../core"
features = ["crypto"]