[package]
name = "opcua-demo-server"
version = "0.3.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]
chrono = "0.4"
log = "0.3"
rand = "0.3"
futures = "0.1.14"
hyper = "0.11.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.opcua-types]
path = "../../types"
version = "0.3.0" # OPCUARustVersion

[dependencies.opcua-core]
path = "../../core"
version = "0.3.0" # OPCUARustVersion

[dependencies.opcua-server]
path = "../../server"
version = "0.3.0" # OPCUARustVersion

