[package]
name = "opcua-core"
version = "0.1.0"
description = "Core components for OPC UA used by client and server"
authors = ["Adam Lock <locka99@gmail.com>"]
homepage = "https://github.com/locka99/opcua"
license = "MPL-2.0"
keywords = ["opcua","opc","ua"]
categories = ["embedded","network-programming"]
readme = "../README.md"

[dependencies]
log = "0.3"
env_logger = "0.4"
chrono = "0.3"
rand = "0.3"
regex = "0.2.1"
openssl = "0.9.15"

[dependencies.opcua-types]
path = "../types"
version = "0.1.0"

[dev-dependencies]
tempdir = "0.3"
rustc-serialize = "0.3.24"