[package]
name = "opcua-core"
version = "0.1.0"
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]
log = "0.3"
byteorder = "0.5"
chrono = "0.3"
rand = "0.3"
regex = "0.2.1"
lazy_static = "0.2"
openssl = "0.9.9"

[dev-dependencies]
tempdir = "0.3"