[package]
name = "opcua-core"
version = "0.1.0"
description = "Core components for OPC UA used by client and server"
authors = ["Adam Lock <locka99@gmail.com>"]
homepage = "https://github.com/locka99/opcua"
license = "MPL-2.0"
keywords = ["opcua","opc","ua"]
categories = ["embedded","network-programming"]

[dependencies]
log = "0.3"
chrono = "0.3"
rand = "0.3"
regex = "0.2.1"
openssl = "0.9.9"

[dependencies.opcua-types]
path = "../types"

[dev-dependencies]
tempdir = "0.3"