[package]
name = "opcua-chess-server"
version = "0.5.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]
uci = "0.1.1"

[dependencies.opcua-types]
path = "../../types"
version = "0.5.0" # OPCUARustVersion

[dependencies.opcua-core]
path = "../../core"
version = "0.5.0" # OPCUARustVersion

[dependencies.opcua-server]
path = "../../server"
version = "0.5.0" # OPCUARustVersion
