[package]
name = "opcua-chess-server"
version = "0.10.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2018"

[dependencies]
uci = "0.1.1"

[dependencies.opcua-rs]
path = "../../lib"
version = "0.10.0" # OPCUARustVersion
features = ["server", "console-logging"]
