[package]
name = "opcua-server"
version = "0.1.0"
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]
log = "0.3"
byteorder = "0.5"
chrono = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"
timer = "0.1.6"
rand = "0.3"

[dependencies.opcua-core]
path = "../core"
