[package]
name = "opcua-web-client"
version = "0.6.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.opcua-client]
path = "../../client"
version = "0.6.0" # OPCUARustVersion

[dependencies.opcua-console-logging]
path = "../../console-logging"
version = "0.6.0" # OPCUARustVersion
