[package]
name = "opcua-sample-server"
version = "0.1.0"
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]
log = "0.3.6"

[dependencies.opcua-core]
path = "../core"

[dependencies.opcua-server]
path = "../server"
