[package]
name = "opcua-simple-client"
version = "0.2.0"
authors = ["Adam Lock <locka99@gmail.com>"]

[dependencies]

[dependencies.opcua-types]
path = "../../types"
version = "0.2.0"

[dependencies.opcua-client]
path = "../../client"
version = "0.2.0"

[dependencies.opcua-core]
path = "../../core"
version = "0.2.0"
