[package]
name = "opcua-integration"
version = "0.5.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]

[features]
default = []

# Integration is not built by default
integration = []

[dependencies]
futures = "0.1"
log = "0.4"
chrono = "0.4"

[dependencies.opcua-types]
path = "../types"
version = "0.5.0" # OPCUARustVersion

[dependencies.opcua-core]
path = "../core"
version = "0.5.0" # OPCUARustVersion

[dependencies.opcua-server]
path = "../server"
version = "0.5.0" # OPCUARustVersion

[dependencies.opcua-client]
path = "../client"
version = "0.5.0" # OPCUARustVersion

[dependencies.opcua-console-logging]
path = "../console-logging"
version = "0.5.0" # OPCUARustVersion